### ISSUE TITLE
可以去掉下载前的确认保存文件名称么？

### ISSUE THREAD

**Issue by Tback1** [wadefelix/SendToAria2#1]
Aria2自己能识别重命名啊，这个设定保存名称反而很浪费下载时间。

另外对于http://bbs.feng.com/read-htm-tid-11466356.html中的下载链接

形如“http://bbs.feng.com/plugin.php?id=attachment_download:tongji&aid=13935382&name=%E5%9C%A3%E7%BB%8F%E7%9A%84%E5%8E%86%E5%8F%B2%EF%BC%88%E9%BB%84%E9%87%91%E7%89%88%EF%BC%89.epub&server=http://att6.weiphone.net&url=201710/08/074212gup42g3d3r4rg883.attach”

的链接 从chrome用其他拓展发送都能直接识别，在ff下直接在web页面添加下载也没问题。用Sendtoaria2传送过去就会下载失败，只能识别到网页。可见js脚本的参数传递因为手工设定下载文件名反而编码错误

**Comment by wadefelix** [comment]
我主要是下载腾讯视频来着， 下载连续几集以及一集的几个分段都要重命名下保持顺序。
暂时把强制重命名去了，不填写文件名也直接发给aria2。

另外是不是右键菜单中添加两条，一条直接发送，一条saveas？

我也是随便写写， 具体怎么更好用也没有多少概念。

**Comment by Tback1** [comment]
添加直接发送和另存为我觉得不错。另存为改为自定文件名更直观？

**Comment by Tback1** [comment]
要做功能的话，估计用NAS的小朋友会希望你添加token识别。

**Comment by Tback1** [comment]
试了一下修改后的版本0.1.2，建议：以后直接发送就不要再弹出重命名的窗口，好么。

**Comment by wadefelix** [comment]
已提交更新。 请等待FF审核后更新
