### ISSUE TITLE
不支持token

### ISSUE THREAD

**Issue by daocang** [wadefelix/SendToAria2#2]
http://token:xxxxxx@localhost:6800/jsonrpc
测试这样的无效

**Comment by wadefelix** [comment]
这个可以加。
另外我想问问， 这些配置有没有同步的需求？ 暂时我都是用localstorage保存的。 要不要换用syncstorage?

**Comment by daocang** [comment]
配置保存方式如果能提供选项最好
localstorage or syncstorage 可选

**Comment by daocang** [comment]
另：今天的更新想尽快试用，谢谢！

**Comment by wadefelix** [comment]
已提交更新。 请等待FF审核后更新

**Comment by daocang** [comment]
已更新，很好用！

**Comment by daocang** [comment]
到卡饭去分享了 [Send to Aria2 WE](http://bbs.kafan.cn/thread-2105818-1-1.html)

**Comment by wadefelix** [comment]
多谢
